const colors = require("tailwindcss/colors");

/** @type {import('tailwindcss').Config} */
module.exports = {
  purge: {
    enabled: true,
    mode: "all",
    content: ["./src/**/*.{html,ts}"],
    safelist: [
      /data-theme$/,
      "hljs",
      "hljs-comment",
      "hljs-quote",
      "hljs-keyword",
      "hljs-selector-tag",
      "hljs-subst",
      "hljs-number",
      "hljs-literal",
      "hljs-variable",
      "hljs-template-variable",
      "hljs-tag",
      "hljs-attr",
      "hljs-string",
      "hljs-doctag",
      "hljs-title",
      "hljs-section",
      "hljs-selector-id",
      "hljs-subst",
      "hljs-type",
      "hljs-class",
      "hljs-name",
      "hljs-attribute",
      "hljs-regexp",
      "hljs-link",
      "hljs-symbol",
      "hljs-bullet",
      "hljs-built_in",
      "hljs-builtin-name",
      "hljs-meta",
      "hljs-deletion",
      "hljs-addition",
      "hljs-emphasis",
      "hljs-strong",
      "label-overlay-*",
      // /(from|via|to|border|bg|text)-(.*)-(\d{1}0{1,2})/, // all color options
      // /(border|bg|text)-(.*)-(100|200|400|700)/, colors with specific value & type
      // /(border|bg|text)-(red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(100|200|400|700)/,
      /(bg)-(red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(100|200)/,
      /(border)-(red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(400)/,
      /(text)-(red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(700)/,
      /(text)-(red|yellow|green|blue|indigo)-(800)/,
      /(text)-(white|black)/,
      /(bg)-(gray)-(700)/,
      /(text)-(lime)-(300)/,
    ],
    options: {
      keyframes: true,
    },
  },
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
    },
    fontFamily: {
      Inter: ["Inter var", "sans-serif"],
    },
    extend: {
      colors: {
        kernindigo: {
          DEFAULT: "#0C052E",
          dark: "#06023b",
          darker: "#4F46E5",
          "darker-1": "#312E81",
          light: "#EEF2FF",
          "dark-1": "#0000F5",
          "dark-2": "#4338CA",
        },
      },
      fontFamily: {
        sans: ["Inter var"],
      },
    },
  },
  plugins: [],
}