import { InboxMailThread, User } from "./types-mail";
import { IconBug, IconUserOff } from "@tabler/icons-react";
import { useEffect, useState } from "react";
import { safeAccess } from "@/submodules/javascript-functions/general";
import { getNewInboxMailsInfo } from "./service-mail";

export const MAIL_LIMIT_PER_PAGE = 8;

const setInitials = (first?: string, last?: string) => {
    const firstInitial = first && first.length > 0 ? first[0].toUpperCase() : "";
    const lastInitial = last && last.length > 0 ? last[0].toUpperCase() : "";
    return firstInitial + lastInitial;
};

export function prepareThreadDisplayData(
    thread: InboxMailThread,
    currentUser: User,
    isAdmin: boolean
): {
    displayName: string;
    displayInitials: string;
    background: string;
    text: string;
    recipientIds: string[];
    DisplayIcon?: React.FC
} {
    let background = "";
    let text = "";
    let displayName = "";
    let displayInitials = "";
    let DisplayIcon: React.FC = null;

    if (!currentUser || !thread) return

    const recipientIds = thread.participantIds.filter(
        id => id !== currentUser.id
    );

    const setColor = (id: string) => {
        [background, text] = uuidToPastelColorWithMatchingFont(id);
    };

    // This should not happen
    if (!thread.latestMail) {
        displayName = "<empty>";
        DisplayIcon = IconUserOff
        background = "#F5F5F5";
        text = "#757575";
    }
    else if (!thread.isAdminSupportThread) {
        if (thread.latestMail.senderId === currentUser.id) {
            displayName = thread.latestMail.recipientNames.map(r => `${r?.first} ${r?.last}`).join(", ");
            const r = thread.latestMail.recipientNames[0];
            displayInitials = setInitials(r?.first, r?.last);
            setColor(recipientIds[0]);
        } else {
            const s = thread.latestMail.senderName;
            const first = s?.first ?? "";
            const last = s?.last ?? "";
            displayName = `${first} ${last}`.trim();
            displayInitials = setInitials(first, last);
            setColor(thread.latestMail.senderId);
        }
    } else if (thread.isAdminSupportThread && thread.metaData?.autoGenerated) {
        if (thread.latestMail.senderId) {
            displayName = thread.latestMail.recipientNames.map(r => `${r?.first} ${r?.last}`).join(", ");
        }
        else {
            displayName = `${thread.latestMail.senderName?.first} ${thread.latestMail.senderName?.last}`;
            DisplayIcon = IconBug
            background = "#FFE5E5";
            text = "#A30000";
        }
    } else if (thread.isAdminSupportThread && isAdmin && thread.latestMail.senderId === currentUser.id) {
        displayName = `${thread.latestMail.senderName?.first} ${thread.latestMail.senderName?.last}`;
        displayInitials = setInitials(thread.latestMail.senderName?.first, thread.latestMail.senderName?.last);
        setColor(thread.latestMail.senderId);

    } else if (thread.isAdminSupportThread && isAdmin) {
        if (thread.latestMail.senderId === currentUser.id && thread.latestMail.recipientNames.length === 0) {
            displayName = `${thread.latestMail.senderName?.first} ${thread.latestMail.senderName?.last}`;
        } else if (thread.latestMail.senderId === currentUser.id) {
            displayName = thread.latestMail.recipientNames.map(r => `${r?.first} ${r?.last}`).join(", ");
            const r = thread.latestMail.recipientNames[0];
            displayInitials = setInitials(r?.first, r?.last);
            setColor(recipientIds[0]);
        } else {
            const s = thread.latestMail.senderName;
            displayName = `${s?.first} ${s?.last}`;
            displayInitials = setInitials(s?.first ?? "", s?.last ?? "");
            setColor(thread.latestMail.senderId ?? thread.createdBy);
        }
    } else {
        if (thread.latestMail.senderId === currentUser.id) {
            displayName = thread.latestMail.recipientNames.map(r => `${r?.first} ${r?.last}`).join(", ");
        } else {
            displayName = `${thread.latestMail.senderName?.first} ${thread.latestMail.senderName?.last}`;
        }
    }

    return {
        displayName,
        displayInitials,
        background,
        text,
        recipientIds,
        DisplayIcon
    };
}

export function isSameDay(d1: Date, d2: Date): boolean {
    return (
        d1.getFullYear() === d2.getFullYear() &&
        d1.getMonth() === d2.getMonth() &&
        d1.getDate() === d2.getDate()
    );
}

export function uuidToPastelColorWithMatchingFont(uuid: string): [string, string] {
    let hash = 0;
    for (let i = 0; i < uuid.length; i++) {
        hash = (hash * 31 + uuid.charCodeAt(i)) >>> 0;
    }

    const hue = hash % 360;
    const saturation = 40 + (hash % 15); // 40–55%
    const lightness = 70 + (hash % 10);  // 70–80%
    const background = hslToHex(hue, saturation, lightness);

    const textLightness = lightness - 40;
    const text = hslToHex(hue, saturation, clamp(textLightness, 20, 90));
    return [background, text];
}

export function hslToHex(h: number, s: number, l: number): string {
    s /= 100;
    l /= 100;

    const k = (n: number) => (n + h / 30) % 12;
    const a = s * Math.min(l, 1 - l);
    const f = (n: number) =>
        l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));

    const toHex = (x: number) =>
        Math.round(255 * x)
            .toString(16)
            .padStart(2, "0");

    return `#${toHex(f(0))}${toHex(f(8))}${toHex(f(4))}`;
}

export function clamp(num: number, min: number, max: number): number {
    return Math.min(Math.max(num, min), max);
}


export function useLocalTranslation(translations: Record<string, any>) {
    const t = (key: string) => {
        const parts = key.split(".");
        let current: any = translations;

        for (const p of parts) {
            const next = safeAccess(current, p);
            if (next === undefined) return key;
            current = next;
        }

        return current;
    };

    return { t };
}

export function useNewMailCount(interval: number = 60000, refreshToken?: any): number {
    const [newMailCount, setNewMailCount] = useState(0);

    useEffect(() => {
        let timer: NodeJS.Timeout;

        function fetchNewMailCount() {
            getNewInboxMailsInfo((result: any) => {
                const count = result?.totalNewInboxMails ?? 0;
                setNewMailCount(count);
            });
        }

        fetchNewMailCount();
        timer = setInterval(fetchNewMailCount, interval);

        return () => clearInterval(timer);
    }, [interval, refreshToken]);

    return newMailCount;
}